#!/bin/sh
# Resolve all dependencies that the project requires to run and test.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Installing development dependencies..."
pip install colorlog prek uv
uv pip install --prerelease=allow -r requirements_test.txt
pip install -e .
